coverage:
  precision: 2
  round: down
  range: 70...100

  status:
    project:
      default:
        target: auto
        threshold: 1
    patch:
      default:
        target: auto
        threshold: 1
    changes: false

comment:
  layout: "header, diff"
  behavior: default  # update if exists else create new
 
codecov:
  strict_yaml_branch: master  # only use the latest copy on master branch
