trigger:
- master

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: '1'
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: 'true'

jobs:

- template: scripts/build.yml
  parameters:
    name: Linux_netstandard20
    displayName: Linux - netstandard2.0
    framework: netstandard2.0
    appFramework: netcoreapp2.1
    pool:
      vmImage: 'ubuntu-latest'

- template: scripts/build.yml
  parameters:
    name: macOS_netstandard20
    displayName: macOS - netstandard2.0
    framework: netstandard2.0
    appFramework: netcoreapp2.1
    pool:
      vmImage: 'macOS-latest'

- template: scripts/build.yml
  parameters:
    name: Windows_netstandard20
    displayName: Windows - netstandard2.0
    framework: netstandard2.0
    appFramework: netcoreapp2.1
    pool:
      vmImage: 'windows-latest'

- template: scripts/build.yml
  parameters:
    name: Windows_net461
    displayName: Windows - net461
    framework: net461
    appFramework: net461
    pool:
      vmImage: 'windows-latest'
