trigger:
- master

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: '1'

jobs:

- template: scripts/build.yml
  parameters:
    name: Linux_netstandard20
    displayName: Linux - netstandard2.0
    framework: netstandard2.0
    appFramework: netcoreapp2.1
    pool:
      vmImage: 'ubuntu-latest'

- template: scripts/build.yml
  parameters:
    name: macOS_netstandard20
    displayName: macOS - netstandard2.0
    framework: netstandard2.0
    appFramework: netcoreapp2.1
    pool:
      vmImage: 'macOS-latest'

- template: scripts/build.yml
  parameters:
    name: Windows_netstandard20
    displayName: Windows - netstandard2.0
    framework: netstandard2.0
    appFramework: netcoreapp2.1
    pool:
      vmImage: 'windows-latest'

- template: scripts/build.yml
  parameters:
    name: Windows_net47
    displayName: Windows - net47
    framework: net47
    appFramework: net47
    pool:
      vmImage: 'windows-latest'
