trigger:
- master

variables:
  DOTNET_CLI_TELEMETRY_OPTOUT: '1'

jobs:

- template: scripts/build.yml
  parameters:
    name: Linux_netstandard20
    displayName: Linux - netstandard2.0
    framework: netstandard2.0
    appFramework: netcoreapp2.0
    pool:
      vmImage: 'ubuntu-latest'

- template: scripts/build.yml
  parameters:
    name: macOS_netstandard20
    displayName: macOS - netstandard2.0
    framework: netstandard2.0
    appFramework: netcoreapp2.0
    pool:
      vmImage: 'macOS-latest'

- template: scripts/build.yml
  parameters:
    name: Windows_netstandard20
    displayName: Windows - netstandard2.0
    framework: netstandard2.0
    appFramework: netcoreapp2.0
    pool:
      vmImage: 'windows-latest'

- template: scripts/build.yml
  parameters:
    name: Windows_net47
    displayName: Windows - net47
    framework: net47
    appFramework: net47
    pool:
      vmImage: 'windows-latest'

- job: pack
  displayName: Pack nupkg
  pool:
    vmImage: 'windows-latest'
  dependsOn:
  - Linux_netstandard20
  - macOS_netstandard20
  - Windows_netstandard20
  - Windows_net47
  
  steps:

  - task: DotNetCoreCLI@2
    displayName: Pack certes
    inputs:
      command: 'pack'
      packagesToPack: 'src/Certes/Certes.csproj'
      includesymbols: true
      versioningScheme: 'off'

  - task: DotNetCoreCLI@2
    displayName: Pack certes.tool
    inputs:
      command: 'pack'
      packagesToPack: 'src/Certes.Cli/Certes.Cli.csproj'
      includesymbols: true
      versioningScheme: 'off'
