trigger:
- master

stages:

- stage: test
  displayName: Test
  jobs:

  - template: scripts/build.yml
    parameters:
      name: Linux_netstandard20
      displayName: Linux - netstandard2.0
      framework: netstandard2.0
      appFramework: netcoreapp2.0
      pool:
        vmImage: 'ubuntu-latest'

  - template: scripts/build.yml
    parameters:
      name: macOS_netstandard20
      displayName: macOS - netstandard2.0
      framework: netstandard2.0
      appFramework: netcoreapp2.0
      pool:
        vmImage: 'macOS-latest'

  - template: scripts/build.yml
    parameters:
      name: Windows_netstandard20
      displayName: Windows - netstandard2.0
      framework: netstandard2.0
      appFramework: netcoreapp2.0
      pool:
        vmImage: 'windows-latest'

  - template: scripts/build.yml
    parameters:
      name: Windows_net47
      displayName: Windows - net47
      framework: net47
      appFramework: net47
      pool:
        vmImage: 'windows-latest'

- stage: pack
  displayName: Pack
  dependsOn: test
  jobs:

  - job: pack_preview
    displayName: Pack Certes preview
    pool:
      vmImage: 'windows-latest'
    
    steps:

    - task: DotNetCoreCLI@2
      displayName: Pack certes preview
      inputs:
        command: 'custom'
        custom: 'pack'
        arguments: 'src/Certes/Certes.csproj -p:CertesPreview=true --include-symbols -c Release'
        includesymbols: true
        versioningScheme: 'off'

    - task: CopyFiles@2
      inputs:
        Contents: 'src/Certes/bin/**/*.nupkg'
        TargetFolder: '$(Build.ArtifactStagingDirectory)'
        flattenFolders: true

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'certes_preview'
        publishLocation: 'Container'

  - job: pack
    displayName: Pack Certes
    pool:
      vmImage: 'windows-latest'
    
    steps:

    - task: DotNetCoreCLI@2
      displayName: Pack certes
      inputs:
        command: 'pack'
        packagesToPack: 'src/Certes/Certes.csproj'
        includesymbols: true
        versioningScheme: 'off'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'certes'
        publishLocation: 'Container'

  - job: pack_tool_preview
    displayName: Pack Certes.Tool preview
    pool:
      vmImage: 'windows-latest'
    
    steps:

    - task: DotNetCoreCLI@2
      displayName: Pack certes.tool preview
      inputs:
        command: 'custom'
        custom: 'pack'
        arguments: 'src/Certes.Cli/Certes.Cli.csproj -p:CertesPreview=true'
        includesymbols: true
        versioningScheme: 'off'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'certes_tool_preview'
        publishLocation: 'Container'

  - job: pack_tool
    displayName: Pack Certes.Tool
    pool:
      vmImage: 'windows-latest'
    
    steps:

    - task: DotNetCoreCLI@2
      displayName: Pack certes.tool
      inputs:
        command: 'pack'
        packagesToPack: 'src/Certes.Cli/Certes.Cli.csproj'
        includesymbols: true
        versioningScheme: 'off'

    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'certes_tool'
        publishLocation: 'Container'
