jobs:

- job: Linux

  pool:
    vmImage: 'ubuntu-latest'

  steps:

  - task: DotNetCoreCLI@2
    displayName: 'build certes'
    inputs:
      command: 'build'
      projects: './src/Certes/Certes.csproj'

- job: macOS

  pool:
    vmImage: 'macOS-latest'

  steps:

  - task: DotNetCoreCLI@2
    displayName: 'build certes'
    inputs:
      command: 'build'
      projects: './src/Certes/Certes.csproj'

- job: Windows

  pool:
    vmImage: 'windows-latest'

  steps:
  
  - task: DotNetCoreCLI@2
    displayName: 'build certes'
    inputs:
      command: 'build'
      projects: './src/Certes/Certes.csproj'
