
parameters:
  name: ''
  displayName: ''
  pool: ''
  framework: ''
  appFramework: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool: ${{ parameters.pool }}

  steps:
      
  - task: DotNetCoreCLI@2
    displayName: 'build unit tests'
    inputs:
      command: 'build'
      projects: 'test/Certes.Tests/Certes.Tests.csproj'
      arguments: '-f ${{ parameters.appFramework }} -p:CliOutputType=Library'
      
  - task: DotNetCoreCLI@2
    displayName: 'run unit tests'
    inputs:
      command: 'test'
      projects: 'test/Certes.Tests/Certes.Tests.csproj'
      arguments: '-f ${{ parameters.appFramework }} --collect "Code Coverage" --no-build'
      
  - task: DotNetCoreCLI@2
    displayName: 'build integration tests'
    inputs:
      command: 'build'
      projects: 'test/Certes.Tests.Integration/Certes.Tests.Integration.csproj'
      arguments: '-f ${{ parameters.appFramework }} -p:CliOutputType=Library'
      testRunTitle: 'Unit Tests'

  - task: DotNetCoreCLI@2
    displayName: 'run integration tests'
    inputs:
      command: 'test'
      projects: 'test/Certes.Tests.Integration/Certes.Tests.Integration.csproj'
      arguments: '-f ${{ parameters.appFramework }} --collect "Code Coverage" --no-build'
      testRunTitle: 'Integration Tests'

