
parameters:
  name: ''
  displayName: ''
  pool: ''
  framework: ''
  appFramework: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool: ${{ parameters.pool }}

  steps:

  # - task: DotNetCoreCLI@2
  #   displayName: 'build certes'
  #   inputs:
  #     command: 'build'
  #     projects: 'src/Certes/Certes.csproj'
  #     arguments: '-f ${{ parameters.framework }}'

  # - task: DotNetCoreCLI@2
  #   displayName: 'Run unit tests'
  #   inputs:
  #     command: 'test'
  #     projects: 'test/Certes.Tests/Certes.Tests.csproj'
  #     arguments: '-f ${{ parameters.appFramework }} --collect "Code Coverage"'
  #     testRunTitle: 'Unit Tests'

  - task: DotNetCoreCLI@2
    displayName: 'Run unit tests'
    inputs:
      command: 'test'
      projects: 'test/Certes.Cli.Tests/Certes.Cli.Tests.csproj'
      arguments: '-f ${{ parameters.appFramework }} --collect "Code Coverage"'
      testRunTitle: 'Unit Tests'
    condition: eq('${{ parameters.appFramework }}', 'netcoreapp2.1')

  # - task: DotNetCoreCLI@2
  #   displayName: 'run integration tests'
  #   inputs:
  #     command: 'test'
  #     projects: 'test/Certes.Tests.Integration/Certes.Tests.Integration.csproj'
  #     arguments: '-f ${{ parameters.appFramework }} --collect "Code Coverage"'
  #     testRunTitle: 'Integration Tests'
