
parameters:
  name: ''
  displayName: ''
  pool: ''
  framework: ''
  appFramework: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool: ${{ parameters.pool }}

  steps:

  - task: DotNetCoreCLI@2
    displayName: 'build certes'
    inputs:
      command: 'build'
      projects: 'src/Certes/Certes.csproj'
      arguments: '-f ${{ parameters.framework }}'

  - task: DotNetCoreCLI@2
    displayName: 'run unit tests'
    inputs:
      command: 'test'
      projects: 'test/Certes.Tests/Certes.Tests.csproj'
      arguments: '-f ${{ parameters.appFramework }}'
      testRunTitle: 'Unit Tests'

  - task: DotNetCoreCLI@2
    displayName: 'run integration tests'
    inputs:
      command: 'test'
      projects: 'test/Certes.Integration/Certes.Integration.csproj'
      arguments: '-f ${{ parameters.appFramework }}'
      testRunTitle: 'Integration Tests'

