
parameters:
  name: ''
  displayName: ''
  projectName: ''
  previewPackage: ''

jobs:
- job: ${{ parameters.name }}
  displayName: ${{ parameters.displayName }}
  pool:
    vmImage: 'windows-latest'

  steps:

  - task: DotNetCoreCLI@2
    displayName: Pack
    inputs:
      command: 'custom'
      custom: 'pack'
      arguments: 'src/${{ parameters.projectName }}/${{ parameters.projectName }}.csproj -p:CertesPreview=${{ parameters.project }} --include-symbols -c Release'

  - task: CopyFiles@2
    displayName: Copy nupkg
    inputs:
      Contents: 'src/${{ parameters.projectName }}/bin/**/*.nupkg'
      TargetFolder: '$(Build.ArtifactStagingDirectory)'
      flattenFolders: true

  - task: PublishBuildArtifacts@1
    displayName: Publish nupkg
    inputs:
      PathtoPublish: '$(Build.ArtifactStagingDirectory)'
      ArtifactName: '${{ parameters.name }}'
      publishLocation: 'Container'
